version: '3.8'
services:
  backend:
    image: services:v4             # Name:Tag
    build:
      context: .
      dockerfile: Dockerfile
    command: 'gunicorn --bind 0.0.0.0:5004 runner:app'
    ports:
      - 5004:5004                      # Expose Port 5000 Externally
    volumes:
      - .:/src/main                # Map current base DIR to DIR inside container
    env_file:
      - ./.env.dev.v4                 # Environment Variable
    depends_on:
      - db

  priceserver:  
    image: price_server:v1             # Name:Tag
    build:
      context: .
      dockerfile: Dockerfile
    command: 'gunicorn --bind 0.0.0.0:5005 price_runner:app'
    ports:
      - 5005:5005                      # Expose Port 5000 Externally
    volumes:
      - .:/src/main                # Map current base DIR to DIR inside container
    env_file:
      - ./.env.dev.price                 # Environment Variable
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always                # Restart Container
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
    volumes:
      - .dbdata:/var/lib/mysql     # Persistent Storage
    ports:
      - 33067:3306

  nginx:
    build: ./web_server/nginx      # Nginx DockerFile and Config - Web Server
    ports:
      - 8001:8001                    # External Port: Internal Nginx Port
    depends_on:
      - backend
