apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: services-vs
spec:
  hosts:
  - "*" # it referes to both the services. where it going to apply the virtual service rule 
  gateways:
  - services-gateway #refers to ingress gateway name
  http:
  - route:
    - destination:
        host: services-app-service
      weight: 10
    - destination:
        host: services-app-service-v2
      weight: 90
