apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-server-v1
  labels:
    app: price-server-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-server-v1
  template:
    metadata:
      labels:
        app: price-server-v1
    spec:
      containers:
      - name: price-server-v1
        image: deepakrico/price_server:v1
        command: ["gunicorn", "--bind", "0.0.0.0:5005", "price_runner:app"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        env:
        - name: VER
          value: "v1"
        - name: RT
          value: "N"
        - name: search_svc
          value: "search-app-svc-v1"
        - name: search_svc_port
          value: "5000"
        - name: email_svc
          value: "email-app-svc-v1"
        - name: email_svc_port
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: price-server-v1
  labels:
    app: price-server-v1
spec:
  selector:
    app: price-server-v1
  type: ClusterIP             # LoadBalancer OR ClusterIP(Default) OR NodePort
  ports:
    - protocol: TCP
      port: 5005              # External connection
      targetPort: 5005        # Internal POD connection
      name: http-app
